### ISSUE TITLE
Revit 2020-2022 do not open after installing pyRevit 4.8.8.

### ISSUE THREAD

**Issue by kendraanth** [eirannejad/pyRevit#1301]
Revit 2020-2022 do not open after installing pyRevit 4.8.8.

This is happening on my test machine, my machine, and others at client firms. 

All versions start to launch properly. You see the splash screen pull up then after a few seconds it crashes and closes out. This is happening in Revit 2020, 2021, and 2022. Once I remove/disable the pyRevit add-in Revit is able to launch properly.

Please help.

**Comment by jkoz73** [comment]
We are having the same issue in our firm with 4.8.8 and Revit 2020/2022.

My machine had worked flawlessly with both Revit 2020 and 2022 with pyRevit 4.8.8 installed from a local copy of the .exe.  After having tested it for months on my machine, we deployed it to the rest of the firm via PDQ deploy as we had done with 4.7.4 (which still works on Revit 2020).

The weird thing is, we didn't have an issue until a couple of days after the deployment.  Then multiple people reported their Revit not opening at all, including me.  We looked at recent Windows updates that might have interfered with it and even a Bluebeam update that had been applied that day.  Rolling back the few Windows updates that occurred during that time didn't fix it nor did uninstalling Blubeam.

I would be happy to provide any additional information that is necessary to troubleshoot this issue.

**Comment by Crosepink** [comment]
Here is a snippet from my revit Journal File related to this: 

' 0:< API_ERROR { : Assembly version conflict in some references in pyRevitRunner assembly
'Addin's module RevitAPIUI of version 21.0.0.0 conflicts with same preloaded module of version 22.0.0.0
'Addin's module RevitAPI of version 21.0.0.0 conflicts with same preloaded module of version 22.0.0.0 } 
' 0:< ::41:: Delta VM: Avail -26 -> 134211566 MB, Used +7 -> 379 MB, Peak +12 -> 384 MB; RAM: Avail -77 -> 23787 MB, Used +22 -> 565 MB, Peak +27 -> 569 MB 
' 0:< GUI Resource Usage GDI: Avail 9830, Used 170, User: Used 166 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.WindowsAPICodePack assembly
'Addin's module mscorlib of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Windows.Forms of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Core of version 3.5.0.0 conflicts with same preloaded module of version 4.0.0.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.WindowsAPICodePack.Shell assembly
'Addin's module mscorlib of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Windows.Forms of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module PresentationFramework of version 3.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module WindowsBase of version 3.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module PresentationCore of version 3.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Drawing of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System.Core of version 3.5.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module WindowsFormsIntegration of version 3.0.0.0 conflicts with same preloaded module of version 4.0.0.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in MadMilkman.Ini assembly
'Addin's module mscorlib of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0 } 
' 0:< ::41:: Delta VM: Avail -12 -> 134211554 MB, Used +3 -> 383 MB; RAM: Avail -7 -> 23781 MB, Used +7 -> 572 MB, Peak +2 -> 572 MB 
' 0:< GUI Resource Usage GDI: Avail 9830, Used 170, User: Used 166 
' 0:< API_ERROR { : Assembly version conflict in some references in System.Reflection.Metadata assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.2.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.5.0 } 
' 0:< ::41:: Delta VM: Avail -12 -> 134211542 MB, Used +2 -> 385 MB, Peak +1 -> 385 MB; RAM: Avail -2 -> 23779 MB, Used +3 -> 576 MB, Peak +3 -> 576 MB 
' 0:< GUI Resource Usage GDI: Avail 9830, Used 170, User: Used 166 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis.CSharp assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.5.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in pyRevitLabs.Common assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.5.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis.VisualBasic assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.5.0 }

**Comment by eirannejad** [comment]
Sounds like a lot of assembly conflicts...Hmmm

**Comment by eirannejad** [comment]
New installers are generated for pyRevit. [See Notes](https://pyrevitlabs.notion.site/pyRevit-CI-CD-92078f5fb72440de8e7b63f00fa72725). Open the ticket again if issue persists

**Comment by casquatch** [comment]
Looks like we are still running into similar issues after updating to 4.8.10.22040. We are able to start Revit, but when opening certain projects we will run into this dialog.
![image](https://user-images.githubusercontent.com/102679398/160884182-244aedba-a6c9-4ff4-84d3-b1e577949d37.png)

Interestingly enough, when we disabled pyRevit, the issue didn't show up. We then tried to just disable the colorized tabs for pyRevit and that seemed to be the catalyst. Seems that the color tabs are causing a graphics issue? This issue was also present on the 4.8.8 version, with the same fix of turning off the color tabs.

I checked the journal of the most recent crash and am still seeing some assembly conflicts, code snippet below. Let me know if you'd like to see the full journal or need any other info.

`' 0:< API_ERROR { : Assembly version conflict in some references in pyRevitLoader.dll assembly
'Addin's module RevitAPI of version 22.0.0.0 conflicts with same preloaded module of version 21.0.0.0
'Addin's module RevitAPIUI of version 22.0.0.0 conflicts with same preloaded module of version 21.0.0.0 } 
' 0:< ::42:: Delta VM: Avail -13 -> 134211294 MB, Used +0 -> 391 MB; RAM: Avail +7 -> 22958 MB, Used +1 -> 591 MB, Peak +0 -> 591 MB 
' 0:< GUI Resource Usage GDI: Avail 9818, Used 182, User: Used 175 
' 0:< API_ERROR { : Assembly version conflict in some references in pyRevitRunner assembly
'Addin's module RevitAPIUI of version 22.0.0.0 conflicts with same preloaded module of version 21.0.0.0
'Addin's module RevitAPI of version 22.0.0.0 conflicts with same preloaded module of version 21.0.0.0 } 
' 0:< ::42:: Delta VM: Avail -28 -> 134211266 MB, Used +8 -> 400 MB, Peak +5 -> 402 MB; RAM: Avail -24 -> 22934 MB, Used +23 -> 615 MB, Peak +24 -> 616 MB 
' 0:< GUI Resource Usage GDI: Avail 9818, Used 182, User: Used 175 
' 0:< API_ERROR { : Assembly version conflict in some references in MadMilkman.Ini assembly
'Addin's module mscorlib of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0
'Addin's module System of version 2.0.0.0 conflicts with same preloaded module of version 4.0.0.0 } 
' 0:< API_ERROR { : Assembly version conflict in some references in System.Reflection.Metadata assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.2.0 } 
' 0:< ::42:: Delta VM: Avail -9 -> 134211257 MB, Used +2 -> 402 MB; RAM: Avail -25 -> 22910 MB, Used +4 -> 619 MB, Peak +3 -> 619 MB 
' 0:< GUI Resource Usage GDI: Avail 9818, Used 182, User: Used 175 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.2.0 } 
' 0:< ::42:: Delta VM: Avail -7 -> 134211251 MB, Used +1 -> 403 MB, Peak +1 -> 403 MB; RAM: Avail +29 -> 22940 MB, Used +2 -> 621 MB, Peak +2 -> 621 MB 
' 0:< GUI Resource Usage GDI: Avail 9818, Used 182, User: Used 175 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis.CSharp assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.2.0 } 
' 0:< ::42:: Delta VM: Avail 134211251 MB, Used +0 -> 404 MB, Peak +0 -> 404 MB; RAM: Avail -13 -> 22927 MB, Used +1 -> 622 MB, Peak +1 -> 622 MB 
' 0:< GUI Resource Usage GDI: Avail 9818, Used 182, User: Used 175 
' 0:< API_ERROR { : Assembly version conflict in some references in pyRevitLabs.Common assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.2.0
'Addin's module OpenMcdf of version 2.2.1.5 conflicts with same preloaded module of version 1.5.2.35413 } 
' 0:< ::42:: Delta VM: Avail -6 -> 134211245 MB, Used 404 MB; RAM: Avail -13 -> 22915 MB, Used +0 -> 623 MB, Peak +0 -> 623 MB 
' 0:< GUI Resource Usage GDI: Avail 9818, Used 182, User: Used 175 
' 0:< API_ERROR { : Assembly version conflict in some references in Microsoft.CodeAnalysis.VisualBasic assembly
'Addin's module System.Collections.Immutable of version 1.2.3.0 conflicts with same preloaded module of version 1.2.2.0 } 
' 0:< ::42:: Delta VM: Avail -32925 -> 134178321 MB, Used +145 -> 550 MB, Peak +182 -> 587 MB; RAM: Avail -139 -> 22777 MB, Used +168 -> 791 MB, Peak +203 -> 827 MB `
