### ISSUE TITLE
Load Error with pyRevit 4.6+ on Revit 2015

### ISSUE THREAD

**Issue by bushclandan** [eirannejad/pyRevit#412]
when starting revit 2015 with 4.6.5, I get the following screen of errors:
![pyrevit errors](https://user-images.githubusercontent.com/25707637/48138665-685aec00-e26a-11e8-9c2e-a82b42cec02e.png)

**Comment by cpercer** [comment]
Similar behavior to issue #401 (closed).  Revit 2018.3 Win 7 Pro
![pyrevit load screen 1](https://user-images.githubusercontent.com/44647473/48143781-26837300-e275-11e8-96fd-42aa33f39024.JPG)
![pyrevit load screen 2](https://user-images.githubusercontent.com/44647473/48143782-26837300-e275-11e8-828b-1e77778653b2.JPG)

**Comment by eirannejad** [comment]
This seems like a complete error mess. There are so many different things wrong.

Would you please:
- [ ] Uninstall pyRevit
- [ ] Confirm that the installation path is deleted completely
- [ ] Open command prompt and run `pyrevit`. You should get an error that says `pyrevit` does not exist
- [ ] Reinstall pyrevit
- [ ] Delete all caches by running `pyrevit caches clear --all` in command prompt
- [ ] Run again and see if you see errors

**Comment by cpercer** [comment]
Yes, I will try all this.  I was also planning on running System File Checker on this machine.  pyRevit is working on another machine with the same setup.

**Comment by bob13333** [comment]
I got the same error, any luck resoving it ?

**Comment by bushclandan** [comment]
Followed steps with no change.  Noticed that pyRevit is NOT setting path?  I am installing to c:\pyRevit-Master and have added "c:\pyRevit-Master\bin" and "c:\pyRevit-Master\pyrevitlib" to the path.

Any other paths that should be set?

**Comment by bob13333** [comment]
FASTOEM denied: Not FirstTime Install
MSI (c) (AC:9C) [20:11:52:533]: Note: 1: 2205 2:  3: AI_ChainedPackage 
MSI (c) (AC:9C) [20:11:52:533]: Note: 1: 2228 2:  3: AI_ChainedPackage 4: SELECT `ChainedPackage` FROM `AI_ChainedPackage` 
MSI (c) (AC:9C) [20:11:59:423]: Doing action: FatalError
Action 20:11:59: FatalError. 
Action start 20:11:59: FatalError.
Action ended 20:12:00: FatalError. Return value 1.
MSI (c) (AC:9C) [20:12:00:871]: Doing action: AI_SHOW_LOG
Action 20:12:00: AI_SHOW_LOG. 
Action start 20:12:00: AI_SHOW_LOG.
MSI (c) (AC:AC) [20:12:00:886]: Invoking remote custom action. DLL: C:\Users\Name\AppData\Local\Temp\MSIB69D.tmp, Entrypoint: LaunchLogFile
Action ended 20:12:00: AI_SHOW_LOG. Return value 1.
MSI (c) (AC:9C) [20:12:00:987]: Doing action: FatalError
Action 20:12:00: FatalError. 
Action start 20:12:00: FatalError.
Action ended 20:12:00: FatalError. Return value 2.
MSI (c) (AC:CC) [20:12:01:002]: Destroying RemoteAPI object.
MSI (c) (AC:34) [20:12:01:002]: Custom Action Manager thread ending.
=== Verbose logging stopped: 11/7/2018  20:12:01 ===

**Comment by eirannejad** [comment]
pyRevit installer does add the bin path to your system paths. Not sure why it's not working on your machine tho :/

**Comment by bushclandan** [comment]
any other paths necessary?  any ideas on a fix?

**Comment by eirannejad** [comment]
No. Add bin path so pyRevit can see `pyrevit` cli tool. I don't have Revit 2015 so haven't tested on it but works on 2016 well.

**Comment by bushclandan** [comment]
done.  I can run "pyrevit env" and get responses.

no help at startup...

**Comment by eirannejad** [comment]
And startup fails after cleaning cache?!

**Comment by bushclandan** [comment]
Yes

Thanks,

Dan
________________________________

**Comment by cpercer** [comment]
Followed instructions for clearing cache and also ran a SFC scan.  No issues with the scan.  Still get the same startup error.

**Comment by bushclandan** [comment]
As a clarification, with the new distribution model, I have to install the revit addin through the CLI, correct?

**Comment by eirannejad** [comment]
pyrevit cli allows you to manage all your local pyrevit clones (including the one copied by the installer) and attach any to any installed Revit. It basically automates the managing of the pyrevit.addin file for you (one of the many things it does)

**Comment by bushclandan** [comment]
Okay, when I ran the attach command, it did create the .addin file.  I am running an sfc now.  I also ran a registry check.  This is a brand new machine so it is really odd.

Any other suggestions?

**Comment by eirannejad** [comment]
Would you please verify `/bin/Nett.dll` exists?

**Comment by bushclandan** [comment]
yes it does.

**Comment by eirannejad** [comment]
Edit `/pyrevitlib/pyrevit/labs.py`
Comment out lines 11 and 20
``` 
11: clr.AddReference('Nett')
20: import Nett
```

Run again and see if it work.

**Comment by bushclandan** [comment]
did not help

**Comment by eirannejad** [comment]
Wha's the new error?

**Comment by bushclandan** [comment]
same as before - a page full of stuff.  looks the same as it did before uninstall/reinstall/clear caches.

<img width="1013" alt="pyrevit errors" src="https://user-images.githubusercontent.com/25707637/48164188-64998a80-e2a7-11e8-851f-bd57eb12bf44.png">

I have also completed the sfc (no errors) and rebooted to make sure nothing is hanging waiting for a restart...

**Comment by eirannejad** [comment]
Okay this is a dll resolution issue. Most probably because you're on a very old Revit version. Let me see if I can find a 2015 version and run some tests.

**Comment by cpercer** [comment]
Should I start a new error report?

**Comment by eirannejad** [comment]
No. I'll revise the name and will keep it open for testing. Hold still. I'll update here when I have more info.

**Comment by bushclandan** [comment]
10-4 and thanks.

**Comment by eirannejad** [comment]
Compatibility with 2015 and 2014 was broken due to API changes. Added a system to use appropriate files for each Revit version on load time. Tested under 2014 and loads well but it's not finished and not ready for 2015. Will work more on it and will publish with 4.6.7 next week,

**Comment by bushclandan** [comment]
Thanks for your consideration in accommodating this legacy version...

Thanks,

Dan

________________________________

**Comment by bushclandan** [comment]
Just uninstalled old version and installed 4.6.8 and am still receiving a screen of errors after attaching pyrevit master to 2015.  Tried it for both --allusers and only myself.

![2018-11-26 16_48_38-greenshot](https://user-images.githubusercontent.com/25707637/49046916-631efc00-f19b-11e8-8713-8b37bac40091.png)

**Comment by eirannejad** [comment]
I'm having a hard time finding the installer for Revit 2015 and 2014. Autodesk doesn't seem to have links to the installers anymore. Do you guys have access to the installer?

**Comment by bushclandan** [comment]
check your email please.

**Comment by eirannejad** [comment]
@bushclandan Hey man. The file that you sent me is only 1/3 of the installer package (hence _003_ in the name)

**Comment by bushclandan** [comment]
OK.  I have it on a zip drive as well.  I'll upload to Dropbox and reshare.

Thanks.

Thanks,

Dan

________________________________

**Comment by bushclandan** [comment]
I’m uploading but it looks to be a couple of days time to complete.  I’ll let you know when it is ready.


Thanks,

Dan

________________________________

**Comment by eirannejad** [comment]
@bushclandan Hey I got a copy of 2015 and installed. Runs fine on mine but I need to do more testing.

**Comment by bushclandan** [comment]
I am trying to install on a brand new machine with only 2015 installed.  Very strange to have this issue on a new machine.

Thanks again, Dan

Thanks,

Dan

________________________________

**Comment by eirannejad** [comment]
Ya I have all other versions installed as well so that might be helping with reaolving the binding error

**Comment by bushclandan** [comment]
Should I try to install a previous version from before the distribution change?

Thanks,

Dan

________________________________

**Comment by eirannejad** [comment]
Load issue has been resolved and will be published on 4.6.9 soon. Some tools might fail due to API changes. Please report those individually to get fixed.
