### ISSUE TITLE
Pyrevit 4.6+ Load Error Revit 2019

### ISSUE THREAD

**Issue by DarioMariuzzi** [eirannejad/pyRevit#429]
Greetings,

I have just installed Pyrevit 4.6.6 as 4.6.5 was giving a load error which results in Pyrevit not loading into Revit 2019. 4.6.6 is also giving a similar error. 

I have included screenshots of the Pyrevit load screen for reference.

Any assistance for this awesome product would be greatly appreciated.

![2018-11-21 10_51_22 pyrevit load 001](https://user-images.githubusercontent.com/45227531/48829919-1ba00680-ed7c-11e8-8da2-5e94d1ff12a2.png)
![2018-11-21 10_51_22 pyrevit load 002](https://user-images.githubusercontent.com/45227531/48829920-1c389d00-ed7c-11e8-9baf-6f29ff8389cf.png)

**Comment by eirannejad** [comment]
Hey would you be able to send me a list of directories under:

`C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework`

Curious to know if the compiler is somehow pulling an older version of `System.dll`

Also please replace the file below with the file in the attached zip and see if this resolves the issue.

`pyrevitlib\pyrevit\loader\basetypes\__init__.py`

[basetypes-init.zip](https://github.com/eirannejad/pyRevit/files/2611508/basetypes-init.zip)

**Comment by DarioMariuzzi** [comment]
Greetings Ehsan,


Thanks for the help.


Folders listed are v3.5 and v4.0


File replaced still results in error. Am rebooting now will retry and screen grab if same

________________________________

**Comment by DarioMariuzzi** [comment]
No Joy,


Have screen grabbed Pyrevit startup

________________________________

**Comment by duynguyen271188** [comment]
please check copy VG
[https://uphinhnhanh.com/image/Cv0W8P](url)

**Comment by duynguyen271188** [comment]
please check VG copy https://uphinhnhanh.com/images/2018/11/30/15839e259a04172eb.jpg

**Comment by eirannejad** [comment]
@duynguyen271188 This is a pyApex issue. It needs to be updated for pyRevit 4.6+. Please test pyRevit itself and not the extensions and let me know if it works

**Comment by cpercer** [comment]
@eirannejad This is the exact same issue I'm having.  I installed CLI v0.2.13 but when I run pyrevit -V I still get v0.2.10.0
![pyrevit v0 2 10](https://user-images.githubusercontent.com/44647473/49461861-56616000-f7ba-11e8-91be-ae3ebfc3235f.JPG)

**Comment by eirannejad** [comment]
@cpercer You have pyRevit installed separately as well. pyRevit includes the CLI tool in the bin directory and the installer adds it to the system %PATH%. Edit your system %PATH% environment variable and remove the path to the installed pyRevit bin directory Or move the pyRevit CLI path higher in the list of paths

![2018-12-04 09_57_29-settings](https://user-images.githubusercontent.com/8197916/49462492-075ffe80-f7ab-11e8-842d-6c280255ca7e.png)

**Comment by cpercer** [comment]
pyrevit -V now shows v0.2.13, but still receiving same load screen error on startup of Revit 2018.3.
![pyrevit v0 2 13](https://user-images.githubusercontent.com/44647473/49464747-6892cc80-f7c1-11e8-98db-177f8b8f7967.JPG)

**Comment by eirannejad** [comment]
@cpercer Ok. Please share the results on `pyrevit env` command here. Thanks!

**Comment by cpercer** [comment]
![pyrevit env](https://user-images.githubusercontent.com/44647473/49465743-e48e1400-f7c3-11e8-9fd7-7d3ad14e1864.JPG)

**Comment by cpercer** [comment]
@eirannejad I'm having the same issue and installing dotnet 4.7.1 did not resolve the issue.

**Comment by eirannejad** [comment]
Did my best at resolving the references to this issue (error in Visual studio). Updates will be published in 4.6.9 this weekend. Please re-open the issue if it persists.

**Comment by wta12** [comment]
Please reopen this issue.
I could not install pyrevit  4.6.9 for 2018 version. I updated from 4.5 with RVT 2017 then completely uninstall Revit then install Revit 2018. Stills same error
![pyrevit](https://user-images.githubusercontent.com/16380735/50571227-727d0080-0d6a-11e9-9d83-5343abbe6ad8.PNG)

![pyrevit_png](https://user-images.githubusercontent.com/16380735/50571228-74df5a80-0d6a-11e9-9999-86691f884695.PNG)

**Comment by cpercer** [comment]
@eirannejad still having the same issue 4.6.9 Revit 2018.3.2
![pyrevit1](https://user-images.githubusercontent.com/44647473/50605414-dba66600-0e87-11e9-97d2-d213d54e833a.JPG)
![pyrevit2](https://user-images.githubusercontent.com/44647473/50605415-dba66600-0e87-11e9-8c05-f677bc1343d3.JPG)
![pyrevit env](https://user-images.githubusercontent.com/44647473/50605416-dba66600-0e87-11e9-8668-4bc7b21f4359.JPG)

**Comment by eirannejad** [comment]
@cpercer This is beyond me! :/ So it's working fine in 2017 but not in 2018?

**Comment by cpercer** [comment]
@eirannejad I get the same errors in 2017.

The problems seem isolated to this machine.  Working fine on another machine.

**Comment by cpercer** [comment]
@eirannejad doing better, but still get errors with 2017 and 2018.

![pyrevit env](https://user-images.githubusercontent.com/44647473/50606294-d8f94000-0e8a-11e9-94cd-5f444c697b6b.JPG)
![pyrevit new](https://user-images.githubusercontent.com/44647473/50606295-d8f94000-0e8a-11e9-851b-430d312681a9.JPG)

**Comment by eirannejad** [comment]
Are you sure you replaced the correct file?? 
`..\pyrevitlib\pyrevit\loader\basetypes\__init__.py`
not 
`..\pyrevitlib\pyrevit\loader\__init__.py`

**Comment by cpercer** [comment]
D'oh! Let's try this again...

Still getting the same errors in 2017 and 2018

![pyrevit env](https://user-images.githubusercontent.com/44647473/50607122-c2081d00-0e8d-11e9-88a0-02b4484fb131.JPG)
![pyrevit1](https://user-images.githubusercontent.com/44647473/50607123-c2081d00-0e8d-11e9-9ac5-4bf7492f424e.JPG)
![pyrevit2](https://user-images.githubusercontent.com/44647473/50607124-c2081d00-0e8d-11e9-8d5c-a417df342f14.JPG)

**Comment by eirannejad** [comment]
Okay. I really need to find a way to be able to replicate this issue. No matter what machine I use, I can't replicate it which is driving me crazy.

**Comment by wta12** [comment]
Do know if I am in similar situation with cpercer: 
I am using mostly portable software for normal work. Some of my key installed SWs are:
- Windows 10 Edu x64 1803
- Visual Studio 2017
- miniconda with Python 3.5
- Office 2016
- VS code Portable
- Kaspersky Total Sec
- Ameio Backupper
- VM player

**Comment by FrenchQuarters** [comment]
I am been having the exact same issue. 
![image](https://user-images.githubusercontent.com/5280440/50714818-ea377d80-103f-11e9-9cee-e1004629a759.png)
![image](https://user-images.githubusercontent.com/5280440/50714847-0804e280-1040-11e9-8b27-84e5ff757bd3.png)

**Comment by eirannejad** [comment]
Hey guys, is there anyway we can chat somewhere so I can quickly gather more info from you and test a few things? Let me know what time works best.

**Comment by FrenchQuarters** [comment]
Sure. would like you to call or chat? my email is adeshpande@eskewdumezripple.com. Write to me and we can take it on from there. Thanks!

**Comment by wta12** [comment]
sent to your email from cn*******86@gmail.com. 
I am at Central time zone. Let me know if I could anything.

**Comment by cpercer** [comment]
I am central time zone as well.  email is cpercer@pickeringfirm.com

**Comment by FrenchQuarters** [comment]
I am in Central Time as well. We can schedule a conference call. I am open most of this week.  Else, is you want to directly call me, feel free to.

Thanks.


ASEEM DESHPANDE, AIA, LEED AP
Senior Associate | Director of Technology

ESKEW+DUMEZ+RIPPLE, APC
2014 AIA National Architecture Firm Award

365 Canal Street Suite 3150
New Orleans LA 70130
504.561.8686
eskewdumezripple.com<http://www.eskewdumezripple.com/>

**Comment by eirannejad** [comment]
Thanks guys. Let's start with @cpercer. I'll send you an invite soon.

**Comment by FrenchQuarters** [comment]
Ehsan,
I realize you asked only @cpercer to try replacing the system.dll. Nonetheless, I went ahead and did that on my machine. But that did not fix the issue. I am still getting the exact error messag across all versions of Revit.


ASEEM DESHPANDE, AIA, LEED AP
Senior Associate | Director of Technology

ESKEW+DUMEZ+RIPPLE, APC
2014 AIA National Architecture Firm Award

365 Canal Street Suite 3150
New Orleans LA 70130
504.561.8686
eskewdumezripple.com<http://www.eskewdumezripple.com/>

**Comment by eirannejad** [comment]
@FrenchQuarters Awesome thanks a lot. I did a few tests on @cpercer's machine today so hence I asked him to do the test. Thanks a lot for the quick feedback!

**Comment by cpercer** [comment]
@eirannejad It's still pulling from v4.5 that we put on my desktop.  When I remove the folder from the desktop, I get the error, "pyRevitloader.dll can not be found."

Also, when I run the compile test from the python terminal no dll is created.

**Comment by eirannejad** [comment]
@FrenchQuarters @cpercer All I'm thinking right now is that this could be an addin conflict with another addin maybe. Could you guys share a list of addins or maybe temp remove all the files (copy to another location temporarily) in `%programdata%/Autodesk/Revit/Addins/2018` and `%appdata%/Autodesk/Revit/Addins/2018` and test with a clean Revit and no addons except pyRevit. (copy back the `pyRevit.addin` manifest file in %appdata%)

**Comment by eirannejad** [comment]
@cpercer open a prompt and run `pyrevit attach master 277 --installed`. It would recreate the addin manifest file that we edited

**Comment by cpercer** [comment]
@eirannejad I removed all add-ins, but the error persists.

**Comment by FrenchQuarters** [comment]
Ehsan,

You are having a bad moment here. But, let me take the opportunity to tell you that you have created one of the most useful, well designed, and well thought out addins for Revit. I have really appreciated having it. Thank you very much for that.
Hopefully you’ll straighten out this bug fast, and I look forward to once again start using this awesome tool.

Thanks!



ASEEM DESHPANDE, AIA, LEED AP
Senior Associate | Director of Technology

ESKEW+DUMEZ+RIPPLE, APC
2014 AIA National Architecture Firm Award

365 Canal Street Suite 3150
New Orleans LA 70130
504.561.8686
eskewdumezripple.com<http://www.eskewdumezripple.com/>

**Comment by eirannejad** [comment]
@FrenchQuarters You made my day! Thanks a lot. Yeah hopefully we'll figure out the root issue soon and will get rid of this nasty bug.

**Comment by eirannejad** [comment]
You have no idea how happy I am to see this error on my machine! Finally tracked down the root cause

![2019-01-08 17_06_15-autodesk revit 2018 3](https://user-images.githubusercontent.com/8197916/50869183-d05fa880-1367-11e9-8fd9-79e7d99609ce.png)

**Comment by eirannejad** [comment]
Okay one more time and hopefully the last. Would you please download and extract the modified `__init__.py` file and:
- overwrite `...\pyrevitlib\pyrevit\loader\basetypes\__init__.py` with this file. There are many `__init__.py` files in these directories so make sure you're replacing the correct one.
- open a prompt and run `pyrevit caches clear --all`
- Launch Revit again

[basetypes-init.zip](https://github.com/eirannejad/pyRevit/files/2738965/basetypes-init.zip)

**Comment by wta12** [comment]
PyRevit loaded in my PC. Great thanks for your effort.

**Comment by FrenchQuarters** [comment]
Yes! Success for me as well!!
Thank you very much Ehsan!


ASEEM DESHPANDE, AIA, LEED AP
Senior Associate | Director of Technology

ESKEW+DUMEZ+RIPPLE, APC
2014 AIA National Architecture Firm Award

365 Canal Street Suite 3150
New Orleans LA 70130
504.561.8686
eskewdumezripple.com<http://www.eskewdumezripple.com/>

**Comment by eirannejad** [comment]
Viva pyRevit community and supporters. Thanks guys for helping me figure out this issue! Closing now and will publish with 4.6.10 tonight.

**Comment by FrenchQuarters** [comment]
Ehsan,

Bad new – the same problem is back with recent version of PyRevit.

[cid:image001.png@01D4CF58.D9DF0390]


ASEEM DESHPANDE, AIA, LEED AP
Senior Associate | Director of Technology

ESKEW+DUMEZ+RIPPLE, APC
2014 AIA National Architecture Firm Award

365 Canal Street Suite 3150
New Orleans LA 70130
504.561.8686
eskewdumezripple.com<http://www.eskewdumezripple.com/>

**Comment by eirannejad** [comment]
That's so odd. Nothing has changed on pyRevit loading mechanism tho. What was the last working version of pyRevit you used?

**Comment by mhmtbdr** [comment]
where is the directory

**Comment by FrenchQuarters** [comment]
The problem autoresolved…!
It happened the first time opening every version of Revit after the installation of PyRevit. But second time on, it worked fine.

Aseem Deshpande, AIA, LEED AP
Senior Associate | Director of Technology

EskewDumezRipple+
AIA National Architecture Firm Award Recipient

365 Canal Street Suite 3150
New Orleans, LA 70130
504.561.8686
eskewdumezripple.com<http://www.eskewdumezripple.com/>

**Comment by Kaqwita** [comment]
Hello, I have problem with Pyrevit (with Make Pattern). I have Revit 2019. Help me please.
![image](https://user-images.githubusercontent.com/59198622/71409807-eab39480-2653-11ea-82bc-d06f7626b97b.png)

**Comment by Kaqwita** [comment]
The problem persisted with version 4.7.4

![image](https://user-images.githubusercontent.com/59198622/71410692-521f1380-2657-11ea-98a1-63afc75d13c4.png)

**Comment by threexe** [comment]
> Okay one more time and hopefully the last. Would you please download and extract the modified `__init__.py` file and:
> 
> * overwrite `...\pyrevitlib\pyrevit\loader\basetypes\__init__.py` with this file. There are many `__init__.py` files in these directories so make sure you're replacing the correct one.
> * open a prompt and run `pyrevit caches clear --all`
> * Launch Revit again
> 
> [basetypes-init.zip](https://github.com/eirannejad/pyRevit/files/2738965/basetypes-init.zip)

Have this problem. Understand it is resolved. Out of my element as soon as I have to do anything with a command prompt. Let's take some baby steps. 

I found the pyrevitlib > pyrevit > loader folder. However there was no basetype folder within that folder. Should I add one and paste the _init_.py file from your zip in there? 
![image](https://user-images.githubusercontent.com/61331314/75301036-872e1a80-57ee-11ea-8994-78b99eb0af71.png)

Thank you for your help with this. 

Emily

**Comment by mbinkerd** [comment]
Hello! I think I'm having a similar problem where I can't install the new pyrevit due to it not being able to delete the old one. I've already gone in and deleted all the pyrevit folders from the previous version, but I'm still getting this error. Please help! (sorry, I have no coding skills)... trying to download pyrevit for Revit2020 - although had previously tried to download for 2019 and had the same error.
Any help greatly appreciated!
Thanks! ~Mish
[trying to load pyrevit - fail MSIE019.LOG](https://github.com/eirannejad/pyRevit/files/4881498/trying.to.load.pyrevit.-.fail.MSIE019.LOG)
