### ISSUE TITLE
Make pattern - object has no attribute 'FillPatternId'

### ISSUE THREAD

**Issue by Intuos5** [eirannejad/pyRevit#871]
**Describe the bug**
When I use the make pattern tool to create a filled region in Revit 2020.2, it gives an error message: 

**Expected behavior**
I expect the tool to make a pattern & filled region, just like it is done on the youtube channel.

**Error**
```
﻿ERROR [pyrevit.revit.db.transaction] Error in Transaction Context. Rolling back changes. | <type 'exceptions.AttributeError'>:'FilledRegionType' object has no attribute 'FillPatternId'
```

ERROR [patmaker] Error creating pattern element. | 'FilledRegionType' object has no attribute 'FillPatternId'

**Desktop**
 - OS: Windows 10
 - pyRevit Version 4.7.4
 - Revit 2020.2

**Additional context**
This issue may also be the culprit in another error message in which one of the default filled regions cannot be converted into a new pattern (e.g. model to detail pattern). Creating patterns from line geometry works fine for me.

**Comment by eirannejad** [comment]
Fixed and will be published with next release

**Comment by quantuan125** [comment]
Hi is this issue fixed? Because I have the same problem. Can't make pattern with any filled regions

**Comment by eirannejad** [comment]
It is. It will be published with the next release this weekend

**Comment by quantuan125** [comment]
@eirannejad I still can't make pattern with two filled regions laying on top of each other, and it is the newest version of pyrevit (4.7.5)

**Comment by eirannejad** [comment]
Do you have an example Revit model that I can test?
